#############################################################################
# Makefile for building: qttwitter
# Generated by qmake (2.01a) (Qt 4.4.0) on: Fri Oct 24 13:10:09 2008
# Project:  qttwitter.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile qttwitter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -IMainWindow -Itwitlib -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainWindowDerived.cpp \
		twitterbackendinterface.cpp \
		MainWindow/mainwindowimpl.cpp \
		twitlib/Core.cpp \
		twitlib/QTwitLib.cpp moc_mainWindowDerived.cpp \
		moc_twitterbackendinterface.cpp \
		moc_mainwindowimpl.cpp \
		moc_Core.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainWindowDerived.o \
		twitterbackendinterface.o \
		mainwindowimpl.o \
		Core.o \
		QTwitLib.o \
		moc_mainWindowDerived.o \
		moc_twitterbackendinterface.o \
		moc_mainwindowimpl.o \
		moc_Core.o \
		qrc_images.o
DIST          = TwitterAPI \
		/usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		qttwitter.pro
QMAKE_TARGET  = qttwitter
DESTDIR       = 
TARGET        = qttwitter

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_imageBrowser.h ui_login.h ui_mainWindow.h ui_sendTwit.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qttwitter.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qttwitter.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qttwitter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qttwitter1.0.0 || $(MKDIR) .tmp/qttwitter1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qttwitter1.0.0/ && $(COPY_FILE) --parents mainWindowDerived.h twitterbackendinterface.h blog/blog.h MainWindow/mainwindowimpl.h twitlib/Core.h twitlib/ITwitReply.h twitlib/QTwitLib.h twitlib/Server.h Ui/imageBrowser.h Ui/login.h Ui/mainWindow.h Ui/sendTwit.h blog/blog.h .tmp/qttwitter1.0.0/ && $(COPY_FILE) --parents images/images.qrc .tmp/qttwitter1.0.0/ && $(COPY_FILE) --parents main.cpp mainWindowDerived.cpp twitterbackendinterface.cpp MainWindow/mainwindowimpl.cpp twitlib/Core.cpp twitlib/QTwitLib.cpp .tmp/qttwitter1.0.0/ && $(COPY_FILE) --parents Ui/imageBrowser.ui Ui/login.ui Ui/mainWindow.ui Ui/sendTwit.ui .tmp/qttwitter1.0.0/ && (cd `dirname .tmp/qttwitter1.0.0` && $(TAR) qttwitter1.0.0.tar qttwitter1.0.0 && $(COMPRESS) qttwitter1.0.0.tar) && $(MOVE) `dirname .tmp/qttwitter1.0.0`/qttwitter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qttwitter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainWindowDerived.cpp moc_twitterbackendinterface.cpp moc_mainwindowimpl.cpp moc_Core.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainWindowDerived.cpp moc_twitterbackendinterface.cpp moc_mainwindowimpl.cpp moc_Core.cpp
moc_mainWindowDerived.cpp: mainWindowDerived.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainWindowDerived.h -o moc_mainWindowDerived.cpp

moc_twitterbackendinterface.cpp: twitlib/ITwitReply.h \
		twitlib/Server.h \
		twitlib/QTwitLib.h \
		twitterbackendinterface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) twitterbackendinterface.h -o moc_twitterbackendinterface.cpp

moc_mainwindowimpl.cpp: mainWindowDerived.h \
		ui_mainWindow.h \
		MainWindow/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow/mainwindowimpl.h -o moc_mainwindowimpl.cpp

moc_Core.cpp: twitlib/ITwitReply.h \
		twitlib/Server.h \
		twitlib/Core.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) twitlib/Core.h -o moc_Core.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images/images.qrc \
		images/questionmark \
		images/user-offline.svg \
		images/help-about.svg \
		images/twhitter_btn_03.png \
		images/twitter_system_tray.png \
		images/application-exit.svg \
		images/Twitter.png \
		images/personal.svg \
		images/remove-profile.svg \
		images/TwitterPostIcon.png \
		images/twhitter_btn_02.png \
		images/configure.svg \
		images/qt.png \
		images/im-status-message-edit.svg \
		images/user-online.svg \
		images/icon.facebook.png \
		images/print.jpeg \
		images/twitter_system_tray_2.0.png \
		images/add-profile.svg \
		images/message-unread.svg
	/usr/bin/rcc -name images images/images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_imageBrowser.h ui_login.h ui_mainWindow.h ui_sendTwit.h
compiler_uic_clean:
	-$(DEL_FILE) ui_imageBrowser.h ui_login.h ui_mainWindow.h ui_sendTwit.h
ui_imageBrowser.h: Ui/imageBrowser.ui
	/usr/bin/uic-qt4 Ui/imageBrowser.ui -o ui_imageBrowser.h

ui_login.h: Ui/login.ui
	/usr/bin/uic-qt4 Ui/login.ui -o ui_login.h

ui_mainWindow.h: Ui/mainWindow.ui
	/usr/bin/uic-qt4 Ui/mainWindow.ui -o ui_mainWindow.h

ui_sendTwit.h: Ui/sendTwit.ui
	/usr/bin/uic-qt4 Ui/sendTwit.ui -o ui_sendTwit.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow/mainwindowimpl.h \
		mainWindowDerived.h \
		ui_mainWindow.h \
		ui_login.h \
		ui_sendTwit.h \
		twitterbackendinterface.h \
		twitlib/ITwitReply.h \
		twitlib/Server.h \
		twitlib/QTwitLib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindowDerived.o: mainWindowDerived.cpp mainWindowDerived.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindowDerived.o mainWindowDerived.cpp

twitterbackendinterface.o: twitterbackendinterface.cpp twitterbackendinterface.h \
		twitlib/ITwitReply.h \
		twitlib/Server.h \
		twitlib/QTwitLib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twitterbackendinterface.o twitterbackendinterface.cpp

mainwindowimpl.o: MainWindow/mainwindowimpl.cpp MainWindow/mainwindowimpl.h \
		mainWindowDerived.h \
		ui_mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindowimpl.o MainWindow/mainwindowimpl.cpp

Core.o: twitlib/Core.cpp twitlib/Core.h \
		twitlib/ITwitReply.h \
		twitlib/Server.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Core.o twitlib/Core.cpp

QTwitLib.o: twitlib/QTwitLib.cpp twitlib/QTwitLib.h \
		twitlib/Server.h \
		twitlib/Core.h \
		twitlib/ITwitReply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QTwitLib.o twitlib/QTwitLib.cpp

moc_mainWindowDerived.o: moc_mainWindowDerived.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindowDerived.o moc_mainWindowDerived.cpp

moc_twitterbackendinterface.o: moc_twitterbackendinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twitterbackendinterface.o moc_twitterbackendinterface.cpp

moc_mainwindowimpl.o: moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindowimpl.o moc_mainwindowimpl.cpp

moc_Core.o: moc_Core.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Core.o moc_Core.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

